---
- name: Update installed packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Install common packages
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present