---
node_exporter_version: "1.12.1"

node_exporter_arch: "linux-amd64"

node_exporter_bin_path: "/usr/local/bin/node_exporter"

node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"

node_exporter_port: 9100

node_exporter_collectors_enabled:
  - systemd
  - processes
  - filesystem
  - cpu
  - meminfo
  - netdev
  - diskstats