---
certbot_email: "igorrosp@gmail.com"
certbot_domain: "igor1.pp.ua"
certbot_webroot: "/var/www/certbot"
certbot_staging: false

nginx_conf_dir: /etc/nginx/conf.d
nginx_drone_upstream: "http://127.0.0.1:8080"
nginx_ssl_cert: "/etc/letsencrypt/live/{{ certbot_domain }}/fullchain.pem"
nginx_ssl_key: "/etc/letsencrypt/live/{{ certbot_domain }}/privkey.pem"